### ISSUE TITLE
Install errors out

### ISSUE THREAD

**Issue by ora** [amithgeorge/AlmaLinux-WSL2#1]
```
PS C:\Zip\WSL> .\Alma-8.exe
Using: C:\Zip\WSL\install.tar.gz
Installing...
ERR: The handle is invalid.
HRESULT: 0x80070006
Press enter to exit...
```

Any idea?  thanks
Win10 21H1 with WSL2

**Comment by amithgeorge** [comment]
I recreated the same steps. It is working fine for me. 

```
PS C:\Zip\WSL> .\Alma-8-test.exe
Using: C:\Zip\WSL\install.tar.gz
Installing...
Installation complete
Press enter to continue...
```

I used the Alma.zip from the latest release. I had to rename the exe to a different name, as I already had a working WSL2 installation with that name. 

From a cursory google search for the error message "ERR: The handle is invalid. HRESULT: 0x80070006", it looks like some kind of generic permission denied message. 

You may test one of the other WSL2 images, to see if it is an issue specific to this image, or common with other images - https://wsldl-pg.github.io/docs/Using-wsldl/

**Comment by ora** [comment]
Thanks, you are correct it was lack of system permissions on the source dir.
